'use strict';

module.exports = {
  4: 'Emergency mode by command',
  5: 'Door Opened (Security Event)',
  6: 'Engine Activated (Security Event)',
  7: 'GPS Disconnected',
  8: 'Location change detected on Ignition is Off',
  11: 'Idle transmission',
  12: 'Disarmed from emergency states',
  13: 'Keypad Locked (wrong codes punched in)',
  14: 'Garage Mode',
  25: 'Speed detected when Ignition is Off',
  27: 'GPS connected',
  31: 'Reply to Command',
  32: 'IP changed / connection up',
  33: 'GPS Navigation Start',
  34: 'Over-speed Start',
  35: 'Idle Speed Start',
  36: 'Distance',
  37: 'Engine Start',
  38: 'GPS Factory Reset (Automatic only)',
  40: 'IP Down',
  41: 'GPS Navigation End',
  42: 'End of Over-speed',
  43: 'End of Idle Speed',
  44: 'Timed Event',
  45: 'Engine Stop',
  46: 'Driver Authentication Update',
  47: 'Driving Without Authentication',
  48: 'Door Close Event',
  49: 'Shock Sensor / Input C Inactive Event. CelloTrack: GP1 Input inactive',
  50: 'Hood Sensor Inactive Event. CelloTrack: GP2 Input inactive',
  51: 'Volume Sensor Inactive Event',
  52: 'Hotwire Sensor Inactive Event',
  53: 'Ignition Off Event',
  54: 'Distress Button Inactive Event',
  55: 'Input B Inactive event',
  56: 'Oil Pressure Sensor Inactive Event',
  57: 'Water Temperature Sensor Inactive Event',
  58: 'Input A Inactive event',
  60: 'External Alarm Inactive Event',
  64: 'Door Open Event',
  65: 'Shock Sensor \ Input C Active Event. CelloTrack: GP1 Input Active',
  66: 'Hood Sensor Active Event. CelloTrack: GP2 Input Active',
  67: 'Volume Sensor Active Event',
  68: 'Hotwire Sensor Active Event',
  69: 'Ignition On Event',
  70: 'Distress Button Active Event',
  71: 'Input B Active Event',
  72: 'Oil Pressure Sensor Active Event',
  74: 'Security unit: Input A Active event',
  76: 'External Alarm Active Event (For TETRA Unit only)',
  80: 'Main Power Disconnected',
  81: 'Main Power Low Level',
  82: 'Backup Battery Disconnected',
  83: 'Backup Battery Low Level',
  84: 'Halt (movement end) event',
  85: 'Go (movement start) event',
  87: 'Main Power Connected (be unconditionally logged upon an initial power up)',
  88: 'Main Power High Level',
  89: 'Backup Battery Connected',
  90: 'Backup Battery High Level',
  99: 'Harsh Braking Sensor Triggered',
  100: 'Sudden Course Change Sensor Triggered',
  101: 'Harsh Acceleration Sensor Triggered',
  104: 'Trigger on General Input',
  105: 'Arm Input triggered ',
  106: 'Disarm Input triggered ',
  107: 'Remote Controller input trigger ',
  108: 'Odometer pulse received ',
  109: 'Unlock Pulse trigger ',
  110: 'Lock Pulse trigger ',
  111: 'Triggers on Blinkers ',
  112: 'One of the protected outputs ',
  144: 'Reset while armed',
  145: 'Wireless Panic button (for RB modification only)',
  150: 'Signal Learned',
  151: 'Learning Failed ',
  152: 'Received Signal A ',
  153: 'Received Signal B ',
  154: 'Received Signal C ',
  155: 'D-Sensor Idle Event',
  156: 'Tilt Alarm Event ',
  158: 'Tamper switch Active Event (For CelloTrack only) ',
  159: 'Tamper switch Inactive Event (For CelloTrack only) ',
  190: 'No Modem Zone entry',
  191: 'Geo-HOT Spot violation',
  200: 'Modem is Auto Hardware Reset (AHR) ',
  201: 'PSP - External Alarm is Triggered ',
  202: 'Wake Up event',
  203: 'Pre-Hibernation event',
  207: 'Radio Off Mode',
  208: 'Header Error',
  209: 'Script Version Error',
  210: 'Unsupported Command',
  211: 'Bad Parameters',
  232: 'External EEPROM Error',
  239: 'Max Error',
  245: 'Upload Mode',
  246: 'Execute Mode',
  247: 'Finish Mode',
  248: 'Post Boot Mode',
  252: 'COM-Location Glancing (CelloTrack Unit only)',
  253: 'Violation of Keep In Fence',
  254: 'Violation of Keep Out Fence',
  255: 'Violation of Way Point'
}
